### PR TITLE
fix: log level messages closing sessions

### LINKED ISSUE #286: `vsphere-iso`: Error closing rest client session
#### Overview of the Issue

Whilst running a `vsphere-iso` build using `v1.2.0` of the plugin, an error is raised during the session `Cleanup()`.

```console
==> vsphere-iso.linux-photon: Built on: 2023-06-15 23:28 UTC
==> vsphere-iso.linux-photon: Built by: HashiCorp Packer 1.9.1'...
==> vsphere-iso.linux-photon: Destroying VM...
    vsphere-iso.linux-photon: Closing sessions ....
    vsphere-iso.linux-photon: Error closing rest client session: DELETE https://sfo-m01-vc01.sfo.rainpole.io/rest/com/vmware/cis/session: 401 Unauthorized
==> vsphere-iso.linux-photon: Running post-processor:  (type manifest)
Build 'vsphere-iso.linux-photon' finished after 3 minutes 38 seconds.

==> Wait completed after 3 minutes 38 seconds

==> Builds finished. The artifacts of successful builds are:
--> vsphere-iso.linux-photon: linux-photon-5.0
--> vsphere-iso.linux-photon: linux-photon-5.0-
Done.
```

#### Reference

https://github.com/hashicorp/packer-plugin-vsphere/pull/272 (cc: @ruospalo)
https://github.com/hashicorp/packer-plugin-vsphere/issues/217

#### Reproduction Steps

Run a build with Packer and the plugin using the versions listed below.

### Packer Version

`v1.9.1`

### Plugin Version and Builders

`v1.2.0`
`vsphere-iso`

### VMware vSphere Version

8.0 Update 1 (`v8.0.1`)

### Guest Operating System

VMware Photon OS 5.0 (or any other)

### Simplified Packer Buildfile

See `main` in [Packer Examples for VMware vSphere.](https://github.com/vmware-samples/packer-examples-for-vsphere/)

### Operating System and Environment Details

Ubuntu 22.04 LTS x64

### Log Fragments and `crash.log` Files

```console
==> vsphere-iso.linux-photon: Built on: 2023-06-15 23:28 UTC
==> vsphere-iso.linux-photon: Built by: HashiCorp Packer 1.9.1'...
==> vsphere-iso.linux-photon: Destroying VM...
    vsphere-iso.linux-photon: Closing sessions ....
    vsphere-iso.linux-photon: Error closing rest client session: DELETE https://sfo-m01-vc01.sfo.rainpole.io/rest/com/vmware/cis/session: 401 Unauthorized
==> vsphere-iso.linux-photon: Running post-processor:  (type manifest)
Build 'vsphere-iso.linux-photon' finished after 3 minutes 38 seconds.

==> Wait completed after 3 minutes 38 seconds

==> Builds finished. The artifacts of successful builds are:
--> vsphere-iso.linux-photon: linux-photon-5.0
--> vsphere-iso.linux-photon: linux-photon-5.0-
Done.
```

### PR DESCRIPTION
**Pull request by ruospalo**
The cleanup method executed at the end of the process calls always an API REST method to delete the active session through a driver's logout:
`DELETE https://${vSphere}/rest/com/vmware/cis/session`

If this the logout is called twice for a user_id session, it shows in the UI an error in the step_connect. 
The first time, the session is cleaned, but the second gives an `401 Unauthorized`, doing nothing. This call is innocuous.

In the cleanup method of step_connect, whenever there is an problem calling to the API REST it is showed to the user, giving a false positive error.

The aim of this PR is to dump the message to the log as a warning, and don't show in the UI.

Closes #286

### CODE REVIEW

**Review by tenthirtyam — APPROVED** [review]

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
Please check the signed-off.

**Comment by ruospalo** [comment]
> Please check the signed-off.

Done. Thank you.

**Review by tenthirtyam — APPROVED** [review]
LGTM! 👍

**Review by nywilken — APPROVED** [review]
This looks good to me. There is a bit of a conflict with @dilyar85 recent changes but I can resolve on merge to get this merged and release.

File: builder/vsphere/common/step_connect.go [hunk 1]
```diff
@@ -71,9 +72,9 @@ func (s *StepConnect) Cleanup(state multistep.StateBag) {
 	driver := state.Get("driver").(driver.Driver)
 	errorRestClient, errorSoapClient := driver.Cleanup()
 	if errorRestClient != nil {
-		ui.Message("Error closing rest client session: " + errorRestClient.Error())
+		log.Printf("[WARN] Couldn't close rest client session. Could be already closed: %s", errorRestClient.Error())
```
Comment (nywilken) [inline builder/vsphere/common/step_connect.go:75]: This is not really an issue because vSphere will automatically close if for whatever reason this failed for some other issue. Is that correct?

File: builder/vsphere/common/step_connect.go [hunk 2]
```diff
@@ -71,9 +72,9 @@ func (s *StepConnect) Cleanup(state multistep.StateBag) {
...
 	}
 	if errorSoapClient != nil {
-		ui.Message("Error closing soap client session: " + errorRestClient.Error())
+		log.Printf("[WARN] Couldn't close rest client session. %s", errorRestClient.Error())
```
Comment (nywilken) [inline builder/vsphere/common/step_connect.go:78]: I believe this is a typo. 
```suggestion
		log.Printf("[WARN] Couldn't close rest client session. %s", errorSoapClient.Error())
```

Comment (tenthirtyam) [reply builder/vsphere/common/step_connect.go:78]: I think there are two typos present here: 

```suggestion
		log.Printf("[WARN] Couldn't close soap client session. %s", errorSoapClient.Error())
```

File: builder/vsphere/common/step_connect.go (hunk 1 above)
Comment (tenthirtyam) [reply builder/vsphere/common/step_connect.go:75]: Perhaps better wording and correction terms.

```suggestion
		log.Printf("[WARN] Unable to close REST client session. May already be closed: %s", errorRestClient.Error())
```

**Comment by srknkcn** [comment]
I have a VCenter and I can not get rid of this 401 Unauthorized message.
All RHEL 9 builds are completed and at the "Importing VM OVF template" stage the error comes.

`==> vsphere-iso.linux-rhel: Built on: 2023-10-09 07:06 UTC
==> vsphere-iso.linux-rhel: Built by: HashiCorp Packer 1.9.4'...
==> vsphere-iso.linux-rhel: Importing VM OVF template linux-rhel-9.2-develop to Content Library 'sfo-w01-lib01' as the item 'linux-rhel-9.2-develop' with the description 'Version: develop
==> vsphere-iso.linux-rhel: Built on: 2023-10-09 07:06 UTC
==> vsphere-iso.linux-rhel: Built by: HashiCorp Packer 1.9.4'...
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepConvertToTemplate'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepCreateSnapshot'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepRemoveCDRom'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepRemoveFloppy'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepShutdown'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepProvision'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepConnect'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepWaitForIp'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepBootCommand'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepRun'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepHTTPServer'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepHTTPIPDiscover'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepAddFloppy'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepCreateFloppy'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepConfigParams'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepAddCDRom'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepConfigureHardware'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepCreateVM'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepRemoteUpload'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepCreateCD'. Press enter to continue. 
2023/10/09 10:22:45 packer-plugin-vsphere_v1.2.1_x5.0_darwin_amd64 plugin: 2023/10/09 10:22:45 Deleting CD disk: /var/folders/89/93rwm56d56n116m_kkdk9dbh0000gn/T/packer1085583386.iso
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepDownload'. Press enter to continue. 
==> vsphere-iso.linux-rhel: Pausing before cleanup of step 'StepConnect'. Press enter to continue. 
    vsphere-iso.linux-rhel: Closing sessions ....
2023/10/09 10:22:54 packer-plugin-vsphere_v1.2.1_x5.0_darwin_amd64 plugin: 2023/10/09 10:22:54 [WARN] Failed to close REST client session. The session may already be closed: DELETE https://x.y.z.com/rest/com/vmware/cis/session: 401 Unauthorized
Build 'vsphere-iso.linux-rhel' errored after 16 minutes 28 seconds: unexpected EOF

==> Wait completed after 16 minutes 28 seconds

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso.linux-rhel: unexpected EOF

==> Builds finished but no artifacts were created.
2023/10/09 10:22:54 packer-plugin-vsphere_v1.2.1_x5.0_darwin_amd64 plugin: panic: runtime error: invalid memory address or nil pointer dereference
2023/10/09 10:22:54 packer-plugin-vsphere_v1.2.1_x5.0_darwin_amd64 plugin: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1d8bfe5]
2023/10/09 10:22:54 packer-plugin-vsphere_v1.2.1_x5.0_darwin_amd64 plugin: 
2023/10/09 10:22:54 packer-plugin-vsphere_v1.2.1_x5.0_darwin_amd64 plugin: goroutine 47 [running]:
2023/10/09 10:22:54 packer-plugin-vsphere_v1.2.1_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/driver.(*VirtualMachineDriver).ImportOvfToContentLibrary(0xc000a609f0, {{{0xc00069c780, 0x50}, {0xc00053f6f8, 0x16}, {0x0, 0x0, 0x0}}, {{0x0, 0x0}, ...}, ...})
2023/10/09 10:22:54 packer-plugin-vsphere_v1.2.1_x5.0_darwin_amd64 plugin:      github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/driver/vm.go:841 +0x445
2023/10/09 10:22:54 packer-plugin-vsphere_v1.2.1_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-vsphere/builder/vsphere/common.(*StepImportToContentLibrary).importOvfTemplate(0xc000168f90?, 0xc000b0c000?)
...`

**Comment by jjjbushjjj** [comment]
same here :(

**Comment by tenthirtyam** [comment]
Please open a new issue for the above 401.
