### PR TITLE
fix: skip unix-style permissions

### LINKED ISSUE #280: Add support to output file permission and ownership
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Allow `vsphere-iso`/`vsphere-clone` to customize the file permission and ownership of the output file.

### PR DESCRIPTION
**Pull request by tenthirtyam**
If running on Windows, do not attempt to apply Unix-style permissions to the artifact output.

Closes #280

### CODE REVIEW

**Review by lbajolet-hashicorp — APPROVED** [review]
Just left a nit, but aside from that LGTM!

File: builder/vsphere/common/output_config.go [hunk 1]
```diff
@@ -37,8 +38,10 @@ func (c *OutputConfig) Prepare(ctx *interpolate.Context, pc *common.PackerConfig
 	if c.OutputDir == "" {
 		c.OutputDir = fmt.Sprintf("output-%s", pc.PackerBuildName)
 	}
-	if c.DirPerm == 0 {
-		c.DirPerm = 0750
+	if runtime.GOOS != "windows" {
+		if c.DirPerm == 0 {
```
[the remark this answers is not in the document]
Comment (tenthirtyam) [reply builder/vsphere/common/output_config.go]: Amended in https://github.com/hashicorp/packer-plugin-vsphere/commit/e75a4aebe9fe929ab2a8e642e65bfda7e49498fd.

File: builder/vsphere/common/output_config.go [hunk 2]
```diff
@@ -37,9 +38,11 @@ func (c *OutputConfig) Prepare(ctx *interpolate.Context, pc *common.PackerConfig
 	if c.OutputDir == "" {
 		c.OutputDir = fmt.Sprintf("output-%s", pc.PackerBuildName)
 	}
-	if c.DirPerm == 0 {
+
+	if runtime.GOOS != "windows" && c.DirPerm == 0 {
 		c.DirPerm = 0750
 	}
+	}
```
Comment (lbajolet-hashicorp) [inline builder/vsphere/common/output_config.go:45]: That one's extra, it should be removed

Comment (tenthirtyam) [reply builder/vsphere/common/output_config.go]: doh!
