### PR TITLE
fix: log errors prior to logout

### LINKED ISSUE #311: CRASH when vsphere-iso is replacing an existing template
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I have a Packer Script that uploads the result image to a Content Library.  The first run, which has a unique name, will work without issue.  When I re-run the script, without any changes, packer crashes.

#### Reproduction Steps

Build a packer script
Run the packer script
[run is successful]
Run the packer script again
[run will crash]

### Packer version

From `packer version`
```
packer version
Packer v1.9.2
```

### Simplified Packer Template

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.
```
packer-iso "template"
...
  convert_to_template = false
  dynamic "content_library_destination" {
    for_each = local.isMain ? [1] : [1]
    content {
      name        = "my.template.0.1.0-rc"
      library     = "my content library"
      description = "Built by Packer..."
      ovf         = false
      destroy     = true
      skip_import = false
    }
  }
...
```

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.
Workstation: Windows 10 21h2, build 19044.3448 with Git-Bash git version 2.42.0.windows.2
vSphere Client version 7.0.3.01400

### Log Fragments and crash.log files

per company policy, uploads are forbidden.

### LINKED ISSUE #316: Panic when attempting to log Logout with an error
#### Overview of the Issue

- Ran into a panic when attempting to create a vSphere template and import into a content library. Noticed there weren't any helpful logs to help troubleshoot.
    - `panic: runtime error: invalid memory address or nil pointer dereference` ..... vm.go:945
    - https://github.com/hashicorp/packer-plugin-vsphere/blob/91e51c0b744025ca8554df6779e12b7f6f8c25f9/builder/vsphere/driver/vm.go#L943-L947

#### Reproduction Steps

Please provide the steps to reproduce the issue.

### Packer Version

Please provide the Packer version.

- `1.9.4`
   
### Plugin Version and Builders

Please provide the plugin version.

- `1.2.1`

Please select the builder.

- [x] `vsphere-iso`
- [] `vsphere-clone`

### VMware vSphere Version

Please provide the VMware vSphere version.

- 7.0.3

### Log Fragments and `crash.log` Files

`panic: runtime error: invalid memory address or nil pointer dereference` ..... vm.go:945

### PR DESCRIPTION
**Pull request by bFekete**
# What

- Adding additional logging 
- Separate method for Logout

# Why

- Ran into a panic when attempting to create a vSphere template and import into a content library. Noticed there weren't any helpful logs to help troubleshoot.
    - `panic: runtime error: invalid memory address or nil pointer dereference` ..... vm.go:945
    - https://github.com/hashicorp/packer-plugin-vsphere/blob/91e51c0b744025ca8554df6779e12b7f6f8c25f9/builder/vsphere/driver/vm.go#L943-L947
 
Closes #316 
Closes #311

### CODE REVIEW

**Comment by tenthirtyam** [comment]
Thank you for adding and linking!

**Comment by tenthirtyam** [comment]
@lbajolet-hashicorp and @nywilken - I'll test this one for the crew this week and report back.

**Comment by nywilken** [comment]
> @lbajolet-hashicorp and @nywilken - I'll test this one for the crew this week and report back.

Sounds good thank you @tenthirtyam

File: builder/vsphere/driver/vm.go [hunk 1]
```diff
@@ -837,8 +837,8 @@ func (vm *VirtualMachineDriver) ImportOvfToContentLibrary(ovf vcenter.OVF) error
 
 	l, err := vm.driver.FindContentLibraryByName(ovf.Target.LibraryID)
 	if err != nil {
-		errLogout := vm.driver.restClient.Logout(vm.driver.ctx)
-		log.Printf("can not logout due to %s ", errLogout.Error())
+		log.Printf("can not find content library due to %v", err)
```
Comment (tenthirtyam) [inline builder/vsphere/driver/vm.go:840]:
```suggestion
		log.Printf("cannot find content library: %v", err)
```

File: builder/vsphere/driver/vm.go [hunk 2]
```diff
@@ -853,8 +853,8 @@ func (vm *VirtualMachineDriver) ImportOvfToContentLibrary(ovf vcenter.OVF) error
 		if ovf.Spec.Description != item.Description {
 			err = vm.driver.UpdateContentLibraryItem(item, ovf.Spec.Name, ovf.Spec.Description)
 			if err != nil {
-				errLogout := vm.driver.restClient.Logout(vm.driver.ctx)
-				log.Printf("can not logout due to %s ", errLogout.Error())
+				log.Printf("can not update content library due to %v", err)
```
Comment (tenthirtyam) [inline builder/vsphere/driver/vm.go:856]:
```suggestion
				log.Printf("cannot update content library: %v", err)
```

File: builder/vsphere/driver/vm.go [hunk 3]
```diff
@@ -881,8 +881,8 @@ func (vm *VirtualMachineDriver) ImportToContentLibrary(template vcenter.Template
 
 	l, err := vm.driver.FindContentLibraryByName(template.Library)
 	if err != nil {
-		errLogout := vm.driver.restClient.Logout(vm.driver.ctx)
-		log.Printf("can not logout due to %s ", errLogout.Error())
+		log.Printf("can not find content library due to %v", err)
```
Comment (tenthirtyam) [inline builder/vsphere/driver/vm.go:884]:
```suggestion
		log.Printf("cannot find content library: %v", err)
```

File: builder/vsphere/driver/vm.go [hunk 4]
```diff
@@ -896,17 +896,17 @@ func (vm *VirtualMachineDriver) ImportToContentLibrary(template vcenter.Template
 	if template.Placement.ResourcePool != "" {
 		rp, err := vm.driver.FindResourcePool(template.Placement.Cluster, template.Placement.Host, template.Placement.ResourcePool)
 		if err != nil {
-			errLogout := vm.driver.restClient.Logout(vm.driver.ctx)
-			log.Printf("can not logout due to %s ", errLogout.Error())
+			log.Printf("can not find resource pool due to %v", err)
```
Comment (tenthirtyam) [inline builder/vsphere/driver/vm.go:899]:
```suggestion
			log.Printf("cannot find resource pool: %v", err)
```

File: builder/vsphere/driver/vm.go [hunk 5]
```diff
@@ -896,17 +896,17 @@ func (vm *VirtualMachineDriver) ImportToContentLibrary(template vcenter.Template
...
 			return err
 		}
 		template.Placement.ResourcePool = rp.pool.Reference().Value
 	}
 	if template.VMHomeStorage != nil {
 		d, err := vm.driver.FindDatastore(template.VMHomeStorage.Datastore, template.Placement.Host)
 		if err != nil {
-			errLogout := vm.driver.restClient.Logout(vm.driver.ctx)
-			log.Printf("can not logout due to %s ", errLogout.Error())
+			log.Printf("can not find datastore due to %v", err)
```
Comment (tenthirtyam) [inline builder/vsphere/driver/vm.go:908]:
```suggestion
			log.Printf("cannot find datastore: %v", err)
```

File: builder/vsphere/driver/vm.go [hunk 6]
```diff
@@ -922,17 +922,17 @@ func (vm *VirtualMachineDriver) ImportToContentLibrary(template vcenter.Template
 	if template.Placement.Folder != "" {
 		f, err := vm.driver.FindFolder(template.Placement.Folder)
 		if err != nil {
-			errLogout := vm.driver.restClient.Logout(vm.driver.ctx)
-			log.Printf("can not logout due to %s ", errLogout.Error())
+			log.Printf("can not find folder due to %v", err)
```
Comment (tenthirtyam) [inline builder/vsphere/driver/vm.go:925]:
```suggestion
			llog.Printf("cannot find folder: %v", err)
```

File: builder/vsphere/driver/vm.go [hunk 7]
```diff
@@ -922,17 +922,17 @@ func (vm *VirtualMachineDriver) ImportToContentLibrary(template vcenter.Template
...
 			return err
 		}
 		template.Placement.Folder = f.folder.Reference().Value
 	}
 	if template.Placement.Host != "" {
 		h, err := vm.driver.FindHost(template.Placement.Host)
 		if err != nil {
-			errLogout := vm.driver.restClient.Logout(vm.driver.ctx)
-			log.Printf("can not logout due to %s ", errLogout.Error())
+			log.Printf("can not find host due to %v", err)
```
Comment (tenthirtyam) [inline builder/vsphere/driver/vm.go:934]:
```suggestion
			log.Printf("cannot find host: %v", err)
```

File: builder/vsphere/driver/vm.go [hunk 8]
```diff
@@ -941,8 +941,8 @@ func (vm *VirtualMachineDriver) ImportToContentLibrary(template vcenter.Template
 	vcm := vcenter.NewManager(vm.driver.restClient.client)
 	_, err = vcm.CreateTemplate(vm.driver.ctx, template)
 	if err != nil {
-		errLogout := vm.driver.restClient.Logout(vm.driver.ctx)
-		log.Printf("can not logout due to %s ", errLogout.Error())
+		log.Printf("can not create template due to %v", err)
```
Comment (tenthirtyam) [inline builder/vsphere/driver/vm.go:944]:
```suggestion
		log.Printf("cannot create template: %v", err)
```

File: builder/vsphere/driver/vm.go [hunk 9]
```diff
@@ -1236,8 +1236,8 @@ func (vm *VirtualMachineDriver) FindContentLibraryTemplateDatastoreName(library
 
 	l, err := vm.driver.FindContentLibraryByName(library)
 	if err != nil {
-		errLogout := vm.driver.restClient.Logout(vm.driver.ctx)
-		log.Printf("can not logout due to %s ", errLogout.Error())
+		log.Printf("can not find content library due to %v", err)
```
Comment (tenthirtyam) [inline builder/vsphere/driver/vm.go:1239]:
```suggestion
		log.Printf("cannot find content library: %v", err)
```

File: builder/vsphere/driver/vm.go [hunk 10]
```diff
@@ -1252,6 +1252,15 @@ func (vm *VirtualMachineDriver) FindContentLibraryTemplateDatastoreName(library
 	return datastores, vm.driver.restClient.Logout(vm.driver.ctx)
 }
 
+func (vm *VirtualMachineDriver) logout() {
+	if vm.driver.restClient == nil {
+		return
+	}
+	if err := vm.driver.restClient.Logout(vm.driver.ctx); err != nil {
+		log.Printf("can not logout due to %s ", err.Error())
```
Comment (tenthirtyam) [inline builder/vsphere/driver/vm.go:1260]:
```suggestion
		log.Printf("cannot logout: %s ", err.Error())
```

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
In Go, it's better to use "cannot" instead of "can not". 

I've made suggestions to update each to look more like the following:

```go
log.Printf("cannot find datastore: %v", err)
```

This message is more concise and follows Go's conventions. The colon (:) is used to separate the error message from the error itself, which makes it easier to understand what caused the error.

**Review by tenthirtyam — APPROVED** [review]
LGTM!

**Review by nywilken — APPROVED** [review]
This looks good to me. Thanks for the fix @bFekete!
 @tenthirtyam thanks for the review and suite of testing. Much appreciated.
